### ISSUE TITLE
分享功能bug

### ISSUE THREAD

**Issue by CNzhouxu** [TopBidder/bug-bounty#104]
![image](https://user-images.githubusercontent.com/24469293/112813089-6cdd0500-90b0-11eb-8743-315371d61ced.png)

分享链接无法使用，点击分享之后，访问分享地址会提示 artwork is not exist

0x4BC0AE26936561cb32B26DAdA4C2Fb0577054100

**Comment by lichking24** [comment]
分享功能仍在开发中。
