### ISSUE TITLE
网站首页围观分享，底部按钮失效

### ISSUE THREAD

**Issue by cjayz001** [TopBidder/bug-bounty#106]
![image](https://user-images.githubusercontent.com/76425476/112812950-428b4780-90b0-11eb-8cd4-3a1d9338e650.png)
![test5](https://user-images.githubusercontent.com/76425476/112813187-83835c00-90b0-11eb-9bfb-948b94b4ea36.JPG)
![test4](https://user-images.githubusercontent.com/76425476/112813222-8d0cc400-90b0-11eb-85fc-cf80b3f0ad49.JPG)
首页的围观，分享，显示全部，以及底部艺术家，矿池，等按钮失效

**Comment by cjayz001** [comment]
ETH地址
0xC3B3152842f12601f344ed5b2cd9bb79ACb0980F

**Comment by lichking24** [comment]
已修复。
