### ISSUE TITLE
个人中心显示异常

### ISSUE THREAD

**Issue by cjayz001** [TopBidder/bug-bounty#107]
![test1](https://user-images.githubusercontent.com/76425476/112813666-0d332980-90b1-11eb-84d6-3057cb03c67c.JPG)
![test2](https://user-images.githubusercontent.com/76425476/112813678-10c6b080-90b1-11eb-96ca-557b3cc77dc2.JPG)
点击个人中心后，会从图1迅速变成图2的界面，没有显示正常的信息。

ETH地址：0xC3B3152842f12601f344ed5b2cd9bb79ACb0980F

**Comment by cjayz001** [comment]
![test1](https://user-images.githubusercontent.com/76425476/112814043-72871a80-90b1-11eb-9994-1fa4414e1b9e.JPG)
顶部规则，交易按键也是无效的，不会跳转链接。

**Comment by lichking24** [comment]
已优化。
