### ISSUE TITLE
Internal Sever Error

### ISSUE THREAD

**Issue by kender1314** [TopBidder/bug-bounty#110]
![image](https://user-images.githubusercontent.com/37035331/112814065-79159200-90b1-11eb-8178-ab4bfe2bfbad.png)
出现服务器报错
![image](https://user-images.githubusercontent.com/37035331/112814152-8c286200-90b1-11eb-89a9-84294a4dfb41.png)
我的地址为 0xc273490bd3BCe68dfB10c67ECF20480251C5F5DB

**Comment by lichking24** [comment]
已修复。
