### ISSUE TITLE
个人中心显示的ETH地址与绑定的ETH地址不一致，且没有拍卖纪录。

### ISSUE THREAD

**Issue by cjayz001** [TopBidder/bug-bounty#115]
![test1](https://user-images.githubusercontent.com/76425476/112814834-461fce00-90b2-11eb-9481-4d3526f7fdd9.JPG)
![test2](https://user-images.githubusercontent.com/76425476/112814840-4750fb00-90b2-11eb-908a-0c8802a65406.JPG)
个人中心显示的ETH地址与绑定的ETH地址不一致，且没有拍卖纪录。

**Comment by cjayz001** [comment]
ETH地址：
0xC3B3152842f12601f344ed5b2cd9bb79ACb0980F

**Comment by lichking24** [comment]
个人中心为艺术家合约，文案已改。
数据统计已修复。
