### ISSUE TITLE
自定义竞拍提交了2.5ETH但是实际还是在原价的基础上增加0.05

### ISSUE THREAD

**Issue by HansiChan** [TopBidder/bug-bounty#119]
https://ropsten.etherscan.io/tx/0xa1d873c88e0f9969ea1f743752b61ed50ec466eea93d32675c5b3373607987c2

**Comment by HansiChan** [comment]
一个人出了更高价竞拍后，其他人还可以出低价竞拍，这个问题应该跟上面提的问题是同一个BUG

**Comment by HansiChan** [comment]
0x2F42fCd8D06A840C242814ea5AaAa60699C3D69c

**Comment by lichking24** [comment]
自定义竞拍的定义已增加提示。
