### ISSUE TITLE
无法支持手机端metamask

### ISSUE THREAD

**Issue by ycl1216919** [TopBidder/bug-bounty#12]
无法支持手机端的metamask。![496BD5B2-BF02-48C0-916C-AF2054284A5D](https://user-images.githubusercontent.com/36100212/112804600-921d4380-90af-11eb-9616-143b9e971394.png)
![6A72F1E4-C1AF-4BBC-93ED-E852DB767E8D](https://user-images.githubusercontent.com/36100212/112804612-947f9d80-90af-11eb-95cc-57355756725e.png)

**Comment by lichking24** [comment]
手机端暂未适配，后续将会提供手机端。
