### ISSUE TITLE
拍卖的方式不是很明确

### ISSUE THREAD

**Issue by dabai4521** [TopBidder/bug-bounty#121]
应该设置拍卖的方式，包括时间（是不是限时拍卖）和方式等等。
在我看来可以搞一些新的方式，比如增加到固定价位（卖者设定的一个公开的价位）自动成交的方式。
ETH地址：0x21207749E7F953BB4415E6d1760D8c5f9ed96bbB

**Comment by dabai4521** [comment]
关于拍卖的方式，我还想到，为了避免买卖时间太长（比如卖价怕卖便宜赚少了不愿意成交），可以平台设定让卖家分享第二第三次的利润的百分之几等方式，让大家共赢，这样不至于买卖的时间过久。
ETH地址：0x21207749E7F953BB4415E6d1760D8c5f9ed96bbB

**Comment by lichking24** [comment]
感谢提议，内容已记录，我们后面针对产品机制讨论一下。
