### ISSUE TITLE
作品详情页

### ISSUE THREAD

**Issue by ABBOOT** [TopBidder/bug-bounty#122]
作品范围 滑动时候漂浮了， 没有进行固定我滑动 他跟着滑动。

**Comment by ABBOOT** [comment]
https://sandbox.bidder.top/#/product/1376206307710865408

**Comment by ABBOOT** [comment]
ETH:0x4012972309aafF4793885EaC13857b6f33851d81

**Comment by lichking24** [comment]
已修复。
