### ISSUE TITLE
我的TopBidder体验——BUG反馈汇总

### ISSUE THREAD

**Issue by zhoukuansky** [TopBidder/bug-bounty#128]
# Bug反馈 
**我的ETH地址：     
0x54E83cE35884aF2E263952f381013757218ecBa7**

这里我大概使用了TopBidder网站的大致功能。这里发现了几个bug。
我这边没看其他Bug提交者们，提交的bug。所以，有些点可能会比较类似。

#### 问题一：竞拍合约问题
> 问题描述：    
当我竞拍一个已经出过价的nft时，合约出现以下错误。建议提前截断。不要调用合约。提升用户体验。     
下面分别是这种情况下的，竞拍和自定义竞拍两种场景下的错误。         

![image](https://user-images.githubusercontent.com/30614105/112811852-0efbed80-90af-11eb-98bf-a65a9d05ce81.png)
![image](https://user-images.githubusercontent.com/30614105/112812174-60a47800-90af-11eb-98be-1997841d110d.png)

#### 问题二：个人中心ETH地址显示问题
> 问题描述：   
我的个人中心，进入以后显示的ETH地址和我实际的ETH地址完全不相同。。。
我实际连接的ETH地址是：       
0x54E83cE35884aF2E263952f381013757218ecBa7    

可是实际显示的却是，如下图所示的ETH地址：    

![image](https://user-images.githubusercontent.com/30614105/112814224-a3674f80-90b1-11eb-8115-63389991fcd8.png)

#### 问题三：   网页UI BUG
> 问题描述：    
这网页UI BUG实在不想吐槽。上图。

![image](https://user-images.githubusercontent.com/30614105/112814959-664f8d00-90b2-11eb-89a4-2fe39d89f74f.png)

#### 问题四：  关于分享的BUG
> 问题描述：     
从第一个分享页面，点击复制链接以后，显示“分享地址已复制到剪切板”。   
但是从这个分享链接进去以后，网页显示如下第二张图。   

![image](https://user-images.githubusercontent.com/30614105/112816181-b7ac4c00-90b3-11eb-8f15-bab0ad2375ee.png)
![image](https://user-images.githubusercontent.com/30614105/112816198-bbd86980-90b3-11eb-9e15-6fec20805025.png)

#### 问题五：  关于排行榜的问题
> 问题描述：  
从排行榜页面点击艺术品以后，本该进入艺术品的详细页面。但是实际情况却是，如下图所示：   

![image](https://user-images.githubusercontent.com/30614105/112816418-fa6e2400-90b3-11eb-8b4e-c08bfec17632.png)

#### 问题六：  关于交易记录的问题
> 问题描述：   
个人的交易记录，做得太粗糙。建议细分。上图。   
建议优化这儿的用户体验。   

![image](https://user-images.githubusercontent.com/30614105/112816795-59339d80-90b4-11eb-829d-6b1c1bfcbf2f.png)

## 0x54E83cE35884aF2E263952f381013757218ecBa7

**Comment by lichking24** [comment]
除分享外，均已修复。
分享功能仍在研发中。
