### ISSUE TITLE
排行榜，个人中心Bug

### ISSUE THREAD

**Issue by xiaobin428** [TopBidder/bug-bounty#130]
排行榜无法查看上榜作者作品详细内容
 个人中心不显示竞拍收藏作品详细内容 
我的地址：0x5F1DbF6B9dbA1B53dA4d7d08996bC866eE9E93E3
<img width="878" alt="1" src="https://user-images.githubusercontent.com/36256369/112817413-fc84b280-90b4-11eb-87df-5f124eb071a6.png">
<img width="956" alt="2" src="https://user-images.githubusercontent.com/36256369/112817426-00183980-90b5-11eb-9dc8-cbf2c5eae36a.png">

**Comment by lichking24** [comment]
已修复。
