### ISSUE TITLE
[逻辑]只有在手动切换网络时提示"当前需要测试网络"

### ISSUE THREAD

**Issue by LidamaoHub** [TopBidder/bug-bounty#131]
![image](https://user-images.githubusercontent.com/6832146/112817501-16be9080-90b5-11eb-860a-6413ed8994f2.png)

如果未看到提示或者直接以mainnet进入应用,则无法获知提示

**Comment by lichking24** [comment]
![image](https://user-images.githubusercontent.com/18138973/113374346-7f508a80-939f-11eb-9ecf-6d5043f4262c.png)
已增加适配网络提示。感谢反馈。
