### ISSUE TITLE
[UI] 藏品列表页面 与 藏品详情页面的收藏者不一致

### ISSUE THREAD

**Issue by defi-father** [TopBidder/bug-bounty#133]
期待：收藏者显示一致，刷新后也不一样

[https://sandbox.bidder.top/#/product/1376448373149798400]（https://sandbox.bidder.top/#/product/1376448373149798400） 详情页显示为 digg ,  而列表页显示为 艺术家本人

**Comment by lichking24** [comment]
已修复。
