### ISSUE TITLE
图片操作

### ISSUE THREAD

**Issue by ABBOOT** [TopBidder/bug-bounty#137]
点击放大按钮 没有效果。
<img width="618" alt="WechatIMG234" src="https://user-images.githubusercontent.com/29647378/112819216-ed9eff80-90b6-11eb-90b4-0e95ff82c0b3.png">

**Comment by ABBOOT** [comment]
ETH:0x4012972309aafF4793885EaC13857b6f33851d81

**Comment by lichking24** [comment]
已修复。
