### ISSUE TITLE
查看全部

### ISSUE THREAD

**Issue by ABBOOT** [TopBidder/bug-bounty#138]
点击之后无效果 不跳转。。
<img width="1291" alt="WechatIMG235" src="https://user-images.githubusercontent.com/29647378/112819329-11fadc00-90b7-11eb-9bb6-5ae7740e80aa.png">

**Comment by ABBOOT** [comment]
ETH:0x4012972309aafF4793885EaC13857b6f33851d81

**Comment by lichking24** [comment]
已修复。
