### ISSUE TITLE
分享按钮不可用

### ISSUE THREAD

**Issue by shanchen** [TopBidder/bug-bounty#14]
作品下方的分享按钮点击不可用
![Snip20210329_4](https://user-images.githubusercontent.com/10860925/112804771-6007e380-90a7-11eb-9b8a-ed8ec23fbd64.png)

ETH : 0xc385f58e9e7f7Dc584EC5a157E110B904Fb62EDC

**Comment by lichking24** [comment]
分享仍在开发中。
