### ISSUE TITLE
测试拍卖后钱包无nft

### ISSUE THREAD

**Issue by aod17596113371** [TopBidder/bug-bounty#140]
[](url)
![微信图片_20210329175418](https://user-images.githubusercontent.com/79297082/112820043-cd237500-90b7-11eb-872b-781fa956c161.png)
![微信图片_20210329175358](https://user-images.githubusercontent.com/79297082/112820048-ce54a200-90b7-11eb-9bfc-fbfd2c096db9.png)

**Comment by aod17596113371** [comment]
eth地址 0xf1915abA3c55ba20258E6AD98760eEce256Eff28

**Comment by aod17596113371** [comment]
补充
![微信图片_20210329175824](https://user-images.githubusercontent.com/79297082/112820718-766a6b00-90b8-11eb-9960-448956774a87.png)
测试的时候经常出现合约错误
还有推特验证有问题
eth地址 0xf1915abA3c55ba20258E6AD98760eEce256Eff28

**Comment by lichking24** [comment]
已修复。
