### ISSUE TITLE
竞拍出价后，可再次出价，metamaskt提示错误

### ISSUE THREAD

**Issue by feifanlucky** [TopBidder/bug-bounty#143]
连续竞拍出价，metamask提示错误。

![微信图片_20210329183725](https://user-images.githubusercontent.com/76777746/112825482-5e95e580-90be-11eb-81d8-6420df257249.png)
0x34d8575Ec66968Ab4EA07F7031Ed6a74C213B704

**Comment by lichking24** [comment]
已修复。屏蔽了自己买自己的情况。
