### ISSUE TITLE
首页的查看全部无法点击、分享按钮点击后不增加次数

### ISSUE THREAD

**Issue by HansiChan** [TopBidder/bug-bounty#144]
![image](https://user-images.githubusercontent.com/20923601/112826709-eb8d6e80-90bf-11eb-84e3-8a2aa3741523.png)
![image](https://user-images.githubusercontent.com/20923601/112826749-fa742100-90bf-11eb-89b9-282341f02b4c.png)
![image](https://user-images.githubusercontent.com/20923601/112827054-69517a00-90c0-11eb-9f61-78e73e4ddb35.png)
0x2F42fCd8D06A840C242814ea5AaAa60699C3D69c

**Comment by lichking24** [comment]
除分享外其他问题已修复。
分享仍在研发中。
