### ISSUE TITLE
界面元素混乱

### ISSUE THREAD

**Issue by code-drinker** [TopBidder/bug-bounty#146]
![image](https://user-images.githubusercontent.com/66254231/112833194-f8629000-90c8-11eb-9bee-6e66bc656e7d.png)

滚轮持续下拉，会出现界面显示混乱的问题，没有做滚轮触底终止事件。

**Comment by code-drinker** [comment]
ETH：0xd1e175aA9675DCD254B392A14234F6E49F3c5172

**Comment by lichking24** [comment]
已优化。
