### ISSUE TITLE
艺术品分享功能中按钮失效

### ISSUE THREAD

**Issue by code-drinker** [TopBidder/bug-bounty#148]
![image](https://user-images.githubusercontent.com/66254231/112833655-98201e00-90c9-11eb-93e3-ae1bda3fceb8.png)
红框中的复制图片和保存图片两个按钮功能失效

**Comment by code-drinker** [comment]
ETH：0xd1e175aA9675DCD254B392A14234F6E49F3c5172

**Comment by lichking24** [comment]
分享仍在开发中，敬请期待
