### ISSUE TITLE
查看全部按钮功能失效

### ISSUE THREAD

**Issue by code-drinker** [TopBidder/bug-bounty#149]
![image](https://user-images.githubusercontent.com/66254231/112833909-edf4c600-90c9-11eb-8b98-e6a94cbd2ffe.png)
红框中的查看全部的功能按钮点击均失效

**Comment by code-drinker** [comment]
ETH：0xd1e175aA9675DCD254B392A14234F6E49F3c5172

**Comment by lichking24** [comment]
已修复。
