### ISSUE TITLE
鼠标悬停图标改进

### ISSUE THREAD

**Issue by code-drinker** [TopBidder/bug-bounty#150]
![image](https://user-images.githubusercontent.com/66254231/112834085-22688200-90ca-11eb-86fe-a9c20dd15130.png)当鼠标悬停在红框中的区域时，鼠标的图标是不是应该变为小白手而不是输入光标。

**Comment by code-drinker** [comment]
ETH：0xd1e175aA9675DCD254B392A14234F6E49F3c5172

**Comment by lichking24** [comment]
已修复。
