### ISSUE TITLE
注册艺术家认证签名失效问题

### ISSUE THREAD

**Issue by gogit2194** [TopBidder/bug-bounty#152]
在注册艺术家，认证Twitter的验证签名环节，再次点“生成签名”但在metamask中拒绝签名，前一次已生成的签名将失效，无法提交签名信息。
复现步骤：
1，在点击“生成签名”后，在metamask中通过交易，发送含此签名A的推；
2，再次点击“生成签名”，但在metamask中点拒绝（此时网页ui显示的原生成签名A未发生改变）；
3，粘贴含有原签名A的推地址进行提交认证；

结果：
将显示验证失败。
重新点击“生成签名”，再于metamask中点签名让交易通过后，用新生成的签名B发送推，就能成功提交签名信息。
MyAddress：0x95F13225b2C32AAb188a3E08A040519794b36690

**Comment by lichking24** [comment]
已修复。流程以优化。
