### ISSUE TITLE
个人信息页头像上传问题

### ISSUE THREAD

**Issue by ghost** [TopBidder/bug-bounty#154]
## 提示不一致
重现:
+ 登录后打开https://sandbox.bidder.top/#/profile
+ 点基本信息-头像 选择大于1MB文件提示:
![](https://gateway.ethswarm.org/files/6b07ac658525f9812b0c993e3b7d3dc40c476fd6c615e030a829d16ca61a1dbc)
## 可上传非图片文件
重现:
+ https://sandbox-api.bidder.top/file/getPublicFile?storageKey=1376515557070868480/1617021850321_nocode.md
##
**eth:** `0xc78444fdffc4010fB84bE2a6A4d1626f7c195f6d`

**Comment by lichking24** [comment]
已修复。预计4.2上线。
