### ISSUE TITLE
收入管理中的显示错误

### ISSUE THREAD

**Issue by pipi333** [TopBidder/bug-bounty#160]
![image](https://user-images.githubusercontent.com/37148466/112849843-079f0900-90dc-11eb-88e5-249134d439eb.png)
我是有BID收入的 但是显示为零
Creampp提交~

**Comment by lichking24** [comment]
已修复。

**Comment by pipi333** [comment]
0xEccC484DD4093F62fC24c4725800013FBc2C1D15
