### ISSUE TITLE
自定义竞拍功能失效

### ISSUE THREAD

**Issue by code-drinker** [TopBidder/bug-bounty#161]
![image](https://user-images.githubusercontent.com/66254231/112849748-f0601b80-90db-11eb-95dd-2ef0896455d3.png)
自定义1eth拍卖，记录显示和竞价竞拍结果一样，竞拍价格依旧是0.25而不是1.
EHT：0xd1e175aA9675DCD254B392A14234F6E49F3c5172

**Comment by lichking24** [comment]
自定义竞拍的意思已增加提示。
