### ISSUE TITLE
[UI] 作为收藏者，可以竞拍自己拥有的藏品，按钮没有disabled

### ISSUE THREAD

**Issue by momodaka** [TopBidder/bug-bounty#162]
### 重现步骤
已经拥有该藏品，再次进入藏品详情页，可以自己竞拍，按钮可以点击，点击metamask提示合约错误，发起交易，交易会失败

### 期望
已经拥有藏品，不能再进行竞拍，前端查询合约状态，disabled按钮

### 

### 截图
![image](https://user-images.githubusercontent.com/30197937/112849629-d58da700-90db-11eb-90f6-af05b80d0250.png)

**Comment by lichking24** [comment]
已修复。屏蔽自己拍自己的按钮。

**Comment by davidqw** [comment]
请留一个ETH地址收取测试奖励 @momodaka

**Comment by momodaka** [comment]
@davidqw 谢谢，0x242dF0066c1117a780bCbdE64568AEFCA85bB729
