### ISSUE TITLE
[UX] stake BID 时候，期望input具有输入max的功能

### ISSUE THREAD

**Issue by defi-father** [TopBidder/bug-bounty#163]
通常的体验，在input框的右侧拥有 max 按钮，帮助用户快速all in

<img width="741" alt="image" src="https://user-images.githubusercontent.com/71958537/112850325-78debc00-90dc-11eb-9b70-45759c89827f.png">

**Comment by lichking24** [comment]
感谢反馈，已记录后续会进行改进。
