### ISSUE TITLE
制作nft过后的页面不能停留原地会随着界面移动

### ISSUE THREAD

**Issue by zhangguotaoc** [TopBidder/bug-bounty#168]
制作nft过后的页面不能停留原地会随着界面自动，挡住其他的东西的视线，建议设置成可以缩小。
![1617028360834](https://user-images.githubusercontent.com/74718086/112852643-b3495880-90de-11eb-8faf-13c79c828738.jpg)

**Comment by lichking24** [comment]
已优化。
