### ISSUE TITLE
合约代码执行异常

### ISSUE THREAD

**Issue by ShushiLi** [TopBidder/bug-bounty#170]
在两种情况下遇到这种提示，一是收藏家不是自己的时候，等几分钟就不异常了，另一种是收藏家是自己，再竞拍，也是合约代码执行异常，这是状态更新问题？
0x8ccFaFd8030B24548EE6193e126E6fA3196f3a69

**Comment by lichking24** [comment]
收藏家不是自己的时候，是有多人同时以同样价格竞拍。此问题已记录，待优化。
是自己的时候，已经屏蔽了自己买自己的入口。

感谢反馈！
