### ISSUE TITLE
申请成为艺术家时验证推特失败

### ISSUE THREAD

**Issue by DriftMousie** [TopBidder/bug-bounty#172]
地址:0x885ea391039e0FA3f6833a1F3B6d7433B5b69bb6
生成签名：欢迎注册TopBidder，竞拍、收藏最出色的加密艺术作品！0x6f1d30b6f0592148078fc62a78f6787cf249a6b2ccf94a05bfd97906fe1b5c14310b42fddc55de081fa621414e6e115865f36554e05f4405a89cf59c543373ca1c  https://bidder.top

推特地址：https://twitter.com/Blackrabbitknig/status/1376546876237881344?s=20

[申请成为艺术家一直无法验证
提示系统错误

>

**Comment by DriftMousie** [comment]
去掉末尾的？s=20后仍然提示系统错误

**Comment by DriftMousie** [comment]
建议直接链接推特认证比较好一点。。

**Comment by DriftMousie** [comment]
![image](https://user-images.githubusercontent.com/39060563/112856403-551e7480-90e2-11eb-9778-ee404cc16971.png)

**Comment by DriftMousie** [comment]
试了大概不下10次都没有认证成功，辛苦官方处理下，另外推特号其实也可以批量注册，建议可以引入多种认证方式，比如BrightID等

**Comment by lichking24** [comment]
twitter认证已修复，认证流程已优化。
