### ISSUE TITLE
个人中心这里没有显示钱包余额的功能，建议增加

### ISSUE THREAD

**Issue by DriftMousie** [TopBidder/bug-bounty#173]
地址0x885ea391039e0FA3f6833a1F3B6d7433B5b69bb6
建议个人头像导航栏这里增加一个显示当前钱包余额的功能，方便大家查询资金，如下图

**Comment by DriftMousie** [comment]
![image](https://user-images.githubusercontent.com/39060563/112857275-44223300-90e3-11eb-9c30-92c524984275.png)

**Comment by lichking24** [comment]
已记录，后续根据产品规划进行优化。感谢反馈！
