### ISSUE TITLE
未登录时候购买，登录后反而没购买记录

### ISSUE THREAD

**Issue by joose-hash** [TopBidder/bug-bounty#174]
未登录时候购买，登录后反而没购买记录
![截屏2021-03-30 01 20 02](https://user-images.githubusercontent.com/75862649/112875055-46da5380-90f6-11eb-8cdc-d1f74c3c7db3.png)
![截屏2021-03-30 01 17 06](https://user-images.githubusercontent.com/75862649/112875062-493cad80-90f6-11eb-977d-dbe65411114a.png)

交易记录
https://ropsten.etherscan.io/tx/0x6b3494338113e0220c652443b0afde21845b2e39c83f2e95fdc0553eba5f35c2

地址
0xD1baCcf90a1f041A9157d79EA1A6f48510759BBb

**Comment by lichking24** [comment]
已修复
