### ISSUE TITLE
有些交易无法购买 艺术品，metamask 提示合约出错，合约代码执行异常

### ISSUE THREAD

**Issue by fpChan** [TopBidder/bug-bounty#175]
## 问题
购买艺术品时  https://sandbox.bidder.top/#/product/1376473468207501312 ，交易价格显示失败，同时metamask 提示合约出错，合约代码执行异常

<img width="1364" alt="截屏2021-03-30 上午7 29 14" src="https://user-images.githubusercontent.com/29588923/112912378-fe3c8d80-9129-11eb-9b1b-7267cf267177.png">

## 个人ETH地址
0xa6a29572fC865B554e710182a76a7F80F339a6DF

**Comment by lichking24** [comment]
此拍品创建时的合约有bug，目前已替换合约。
