### ISSUE TITLE
拍品详情页面未能显示 交易金额等数据

### ISSUE THREAD

**Issue by fpChan** [TopBidder/bug-bounty#176]
## 问题描述
https://sandbox.bidder.top/#/product/1376490793027637248  
以下数据显示均是一根横线

- 交易金额  ——
- 竞拍次数 ——
- 收藏时长 ——

<img width="1265" alt="截屏2021-03-30 上午7 54 20" src="https://user-images.githubusercontent.com/29588923/112914018-8b351600-912d-11eb-9047-fee04ada9262.png">

## 个人ETH地址

0xa6a29572fC865B554e710182a76a7F80F339a6DF

**Comment by lichking24** [comment]
已修复。
