### ISSUE TITLE
关于TopBidder的测试体验问题

### ISSUE THREAD

**Issue by btc990521** [TopBidder/bug-bounty#18]
#对于手机用户是一件很苦恼的事情,页面没有做到很好的适配.
#未开始的拍卖品也可以点击
#个人主页不显示已经购买或者被购买的商品
#鼠标变成小手问题

**Comment by btc990521** [comment]
我的地址:0xebf6CAF61dAF53dC92B6a9B030Cf642FD4c1103c

**Comment by lichking24** [comment]
手机版暂未适配，后续会进行适配。
其他问题已修复。
