### ISSUE TITLE
自己持有的艺术品，到底能否再买？

### ISSUE THREAD

**Issue by dorispu** [TopBidder/bug-bounty#182]
自己持有的艺术品可以拍，但提示合约错误？
要么不能拍，要么让我成功拍啊～

0x482dd329bC6459DF0302DC987188fb1d34efC24C

**Comment by davidqw** [comment]
目前是不可以拍自己已经持有的作品，产品设计如此

**Comment by lichking24** [comment]
不能买。已修复。
