### ISSUE TITLE
界面元素出格

### ISSUE THREAD

**Issue by code-drinker** [TopBidder/bug-bounty#184]
![image](https://user-images.githubusercontent.com/66254231/112931871-84b79600-914f-11eb-87f1-e408c5880f07.png)
在鼠标滚轮缓慢下滚的时候，在临近底部的时刻会出现界面中的组件元素超出底部栏的现象。
ETH：0xd1e175aA9675DCD254B392A14234F6E49F3c5172

**Comment by lichking24** [comment]
已修复
