### ISSUE TITLE
底部工具栏“矿池”选项跳转显示异常

### ISSUE THREAD

**Issue by code-drinker** [TopBidder/bug-bounty#185]
![image](https://user-images.githubusercontent.com/66254231/112932142-fdb6ed80-914f-11eb-89a6-ea2c33855d99.png)
点击底部工具栏的矿池选项时，跳转到的页面显示如图所示，未能显示全部的页面组件。
ETH：0xd1e175aA9675DCD254B392A14234F6E49F3c5172

**Comment by lichking24** [comment]
已修复
