### ISSUE TITLE
艺术品详情页分享按钮bug

### ISSUE THREAD

**Issue by hayoial** [TopBidder/bug-bounty#187]
进入任一艺术品详情页，点击分享按钮。显示的是“分享图片”，但实际上生成的并不是图片格式，用户无法直接保存图片。
![Snipaste_2021-03-30_15-03-13](https://user-images.githubusercontent.com/25797796/112947225-20093500-9169-11eb-9075-670ba04e69b9.png)

**Comment by lichking24** [comment]
分享仍在开发中，敬请期待
