### ISSUE TITLE
个人中心显示bug

### ISSUE THREAD

**Issue by hayoial** [TopBidder/bug-bounty#188]
bug1:刚刚成功拍下的藏品，不显示在“收藏”菜单，却出现在“被买走的”菜单内。
不仅如此，既然出现在这栏了，“被买走的”本该显示数量1，也只显示0.

bug2:
成交十多分钟后，个人中心显示的收藏总值，收藏数量，收藏均值，均没有及时更新。

**Comment by lichking24** [comment]
已修复。
