### ISSUE TITLE
自定义竞拍

### ISSUE THREAD

**Issue by newgitname** [TopBidder/bug-bounty#19]
自定义竞拍： 输入价格 点击确认竞拍 调用钱包 提示合约代码执行异常
![截屏2021-03-29 下午3 58 55](https://user-images.githubusercontent.com/44631164/112805039-acebba00-90a7-11eb-87cc-95315cf7d0a9.png)

**Comment by newgitname** [comment]
我的地址是 0xB3cfaa16368A907BF8f195E27edA60b0477a8a5c

**Comment by lichking24** [comment]
有问题的合约已替换。
