### ISSUE TITLE
邮箱绑定不成功

### ISSUE THREAD

**Issue by chenbo19931226** [TopBidder/bug-bounty#190]
![image](https://user-images.githubusercontent.com/20835802/112962489-02dc6280-9179-11eb-9763-925ebac71630.png)
![image](https://user-images.githubusercontent.com/20835802/112962543-11c31500-9179-11eb-957c-dd0760b5f3b0.png)

**Comment by chenbo19931226** [comment]
0x4141023B1505294160f4eD0aB92496C8324d8A39

**Comment by c-gongzhihui** [comment]
已修复
