### ISSUE TITLE
申请成为艺术家时发生签名tweet地址错误

### ISSUE THREAD

**Issue by Ztingson** [TopBidder/bug-bounty#192]
0x9Dba31754cd11d55C9BE4BC4d166b3e96aa4D79C
申请成为艺术家时发生签名tweet地址错误，信息提示”get tweet failed"

**Comment by Ztingson** [comment]
[
![捕获](https://user-images.githubusercontent.com/11910030/112964044-89de0a80-917a-11eb-94d2-ea30bfaca5f7.PNG)
](url)

**Comment by c-gongzhihui** [comment]
已修复

**Comment by c-gongzhihui** [comment]
已修复
