### ISSUE TITLE
艺术家发布作品选择图片时，不能调节图片尺寸，无法显示完整图片。

### ISSUE THREAD

**Issue by LILUZIO** [TopBidder/bug-bounty#195]
<img width="1405" alt="WX20210330-165131@2x" src="https://user-images.githubusercontent.com/21023350/112965460-dc6bf680-917b-11eb-9961-e66935a295e2.png">
艺术家发布作品选择图片时，不能调节图片尺寸，存在无法显示完整图片问题。 0x36FBa413ffE9e56130223437c8d49cfCFc7FA276

**Comment by c-gongzhihui** [comment]
已修复
