### ISSUE TITLE
分享艺术品是无法保存生成的分享图片

### ISSUE THREAD

**Issue by Ztingson** [TopBidder/bug-bounty#197]
0x9Dba31754cd11d55C9BE4BC4d166b3e96aa4D79C
[
![捕获](https://user-images.githubusercontent.com/11910030/112965508-e857b880-917b-11eb-851a-042de9764947.PNG)
](url)

点击分享后，该分享页面无法保存，也没有转发按钮

**Comment by lichking24** [comment]
分享仍在开发中，敬请期待
