### ISSUE TITLE
艺术家编辑个人信息页面，上传头像大于1MB后，提示与描述不符。

### ISSUE THREAD

**Issue by LILUZIO** [TopBidder/bug-bounty#198]
<img width="733" alt="WX20210330-171346@2x" src="https://user-images.githubusercontent.com/21023350/112965747-1fc66500-917c-11eb-896d-ac32688b3a54.png">
0x36FBa413ffE9e56130223437c8d49cfCFc7FA276

**Comment by lichking24** [comment]
已修复。
