### ISSUE TITLE
排行榜，点击按价格排序时，报错。

### ISSUE THREAD

**Issue by JeremyGaoMing** [TopBidder/bug-bounty#20]
![image](https://user-images.githubusercontent.com/16744941/112804911-8a59a100-90a7-11eb-8518-dfe3c72e9d9f.png)
排行榜，TOP艺术品TAB页，点击按价格排序时，弹出框JS报错。
ETH address :0x23ee739530231e7aFF44A386DcBab639a6C04c92

**Comment by lichking24** [comment]
已修复。
