### ISSUE TITLE
艺术品信息显示不全，滚动条滑倒底才能看完整

### ISSUE THREAD

**Issue by Ztingson** [TopBidder/bug-bounty#200]
0x9Dba31754cd11d55C9BE4BC4d166b3e96aa4D79C

[
![1](https://user-images.githubusercontent.com/11910030/112966462-d7f40d80-917c-11eb-9c7d-a9c0a2316729.PNG)
](url)

[
![2](https://user-images.githubusercontent.com/11910030/112966483-dc202b00-917c-11eb-8351-ed69a8990945.PNG)
](url)

**Comment by lichking24** [comment]
已记录，后续将进行产品设计优化。感谢反馈。
