### ISSUE TITLE
艺术品详情页面，无法上传图片（但提供了这个选项）

### ISSUE THREAD

**Issue by fpChan** [TopBidder/bug-bounty#202]
## 问题描述
创建艺术品之时，填写详情可以上传图片，但上传失败

![截屏2021-03-30 下午5 39 25](https://user-images.githubusercontent.com/29588923/112969244-a6307600-917f-11eb-9af4-6a6a49933776.png)

## 个人ETH地址

0xa6a29572fC865B554e710182a76a7F80F339a6DF

**Comment by lichking24** [comment]
此处已修改。
bug修复。
