### ISSUE TITLE
艺术家页面，艺术家合约这里错位

### ISSUE THREAD

**Issue by vD1S** [TopBidder/bug-bounty#203]
应该是一行。
![Snipaste_2021-03-30_18-24-44](https://user-images.githubusercontent.com/26621506/112974663-4dfc7280-9185-11eb-95a6-d02e72dbe36e.jpg)

0xa382BB56dB82c6d914880CeA7762CE87b5095bB9

**Comment by lichking24** [comment]
已修复。
