### ISSUE TITLE
艺术家发布作品页面，设置竞拍开始时间功能，存在漏洞。

### ISSUE THREAD

**Issue by LILUZIO** [TopBidder/bug-bounty#205]
<img width="1027" alt="WX20210330-200108@2x" src="https://user-images.githubusercontent.com/21023350/112985867-578cd700-9193-11eb-9ada-f1568c7ae2e6.png">

艺术家发布作品页面，设置竞拍开始时间功能，存在漏洞和逻辑错误；
选择好竞拍开始时间后，无法自动关闭选择框，应在选择好时间后自动确认并关闭选择框，或应在选择框内增加确认按钮。

**Comment by LILUZIO** [comment]
0x36FBa413ffE9e56130223437c8d49cfCFc7FA276

**Comment by lichking24** [comment]
已修复。
修复版本 0.0.14
