### ISSUE TITLE
厂牌添加艺术家页面，无法删除已添加艺术家。

### ISSUE THREAD

**Issue by lowlessakierra** [TopBidder/bug-bounty#206]
<img width="840" alt="WX20210330-203653@2x" src="https://user-images.githubusercontent.com/81628802/112990164-53af8380-9198-11eb-92e8-c98c1f8fd16c.png">
厂牌添加艺术家页面，无法删除已添加艺术家。
0x60c4e100EDbe6CDfb0Dd22878e115e0Eee1786f8

**Comment by lichking24** [comment]
已修复。
