### ISSUE TITLE
厂牌添加艺术家页面，可重复添加艺术家。

### ISSUE THREAD

**Issue by lowlessakierra** [TopBidder/bug-bounty#207]
<img width="756" alt="WX20210330-204750@2x" src="https://user-images.githubusercontent.com/81628802/112990957-362ee980-9199-11eb-83d9-905710d7871a.png">
厂牌添加艺术家页面，未进行ID验证，可重复添加艺术家。
0x60c4e100EDbe6CDfb0Dd22878e115e0Eee1786f8

**Comment by lichking24** [comment]
已修复。
