### ISSUE TITLE
厂牌添加艺术家，只能添加5名，但是页面未说明。

### ISSUE THREAD

**Issue by lowlessakierra** [TopBidder/bug-bounty#209]
<img width="796" alt="WX20210330-205135@2x" src="https://user-images.githubusercontent.com/81628802/112991494-c3723e00-9199-11eb-8e09-ecaa771f1653.png">

厂牌添加艺术家，只能添加5名，但是页面未说明。
0x60c4e100EDbe6CDfb0Dd22878e115e0Eee1786f8

**Comment by lichking24** [comment]
已修复。
