### ISSUE TITLE
MetaMask手机钱包浏览页面显示不全

### ISSUE THREAD

**Issue by bld2018** [TopBidder/bug-bounty#21]
![Screenshot_2021-03-29-16-00-03-214_io metamask](https://user-images.githubusercontent.com/35189867/112805218-ecc88800-903a-11eb-8663-5d3c82c4e2bc.jpg)

**Comment by bld2018** [comment]
0x6b69417C8327407F97E3616619f1826540c1c7D0

**Comment by lichking24** [comment]
手机版页面正在开发中，后续将完成适配。
