### ISSUE TITLE
个人界面中“被买走的”数量显示不正确

### ISSUE THREAD

**Issue by vance46** [TopBidder/bug-bounty#214]
我之前有买过一个，然后被买走了之后，一段时间看到的是“被买走的（1）”。但是过了一会儿再刷新，发现显示的数字是0但是列表里面有之前被买走的记录。
![image](https://user-images.githubusercontent.com/6101296/113027936-a2274700-91c5-11eb-9b29-327a25a0646e.png)

eth addr：0x6bf0443aE7288a126C7a798572ad43Ae78C62b6F
艺术家合约地址：0xa89ffbf57dbc65a383cbb4651ecbc3c69381fdcd

**Comment by lichking24** [comment]
已修复。
