### ISSUE TITLE
注册成为艺术家等待时间段个人中心功能失效

### ISSUE THREAD

**Issue by code-drinker** [TopBidder/bug-bounty#215]
![image](https://user-images.githubusercontent.com/66254231/113085380-446d1c00-9212-11eb-8ca4-6433ea5168ba.png)
当完成验证注册成为艺术家等待系统审核的时候，点击顶部工具栏个人头像下拉菜单的个人中心，跳转不到相应的页面，一直显示艺术家注册中的页面
ETH：0xd1e175aA9675DCD254B392A14234F6E49F3c5172

**Comment by lichking24** [comment]
已修复。
