### ISSUE TITLE
点击成为申请艺术家后，页面一直显示等待

### ISSUE THREAD

**Issue by DriftMousie** [TopBidder/bug-bounty#216]
点击成为申请艺术家后，页面一直显示等待，无法跳转（等待了大约5分组），但新点开页面后已经成功认证为艺术家、
操作系统：win10 使用钱包 metamask 浏览器插件版 使用浏览器Google Chrome版本 89.0.4389.90（正式版本） （64 位）
钱包地址0x885ea391039e0FA3f6833a1F3B6d7433B5b69bb6
![image](https://user-images.githubusercontent.com/39060563/113164409-a9a52980-9273-11eb-9684-2618a021bc0e.png)
![image](https://user-images.githubusercontent.com/39060563/113164442-b0cc3780-9273-11eb-9e5a-79468b82d090.png)

**Comment by lichking24** [comment]
已修复。
修复版本 0.0.14

**Comment by DriftMousie** [comment]
> 已修复。
> 修复版本 0.0.14

真棒
