### ISSUE TITLE
已经拍下藏品，在藏品详情页看到由我收藏了，但是在个人中心却显示没有藏品

### ISSUE THREAD

**Issue by Fsud** [TopBidder/bug-bounty#217]
<img width="1129" alt="WX20210401-000331@2x" src="https://user-images.githubusercontent.com/11521391/113175294-d9f1c580-927d-11eb-9815-457fc8718c04.png">
<img width="1118" alt="WX20210401-000350@2x" src="https://user-images.githubusercontent.com/11521391/113175506-11f90880-927e-11eb-9d42-5b38bfac0bff.png">

地址：0xaDBB884cBE72c934bf54B29430d73c5e844fFCCA

**Comment by lichking24** [comment]
已修复。
