### ISSUE TITLE
近期热拍的作品艺术家和收藏家都展示的是艺术家

### ISSUE THREAD

**Issue by jolestar** [TopBidder/bug-bounty#218]
![Screen Shot 2021-04-01 at 09 25 36](https://user-images.githubusercontent.com/77268/113231011-d8032300-92cc-11eb-9f32-4cba55a11cb5.png)
0xF962f8D31b4f5e9794C76658b8E09aE08B4F0506

**Comment by lichking24** [comment]
是因为从未被没有被买走时候，默认的收藏家就是艺术家自己。

**Comment by jolestar** [comment]
> 是因为从未被没有被买走时候，默认的收藏家就是艺术家自己。

有被买走呀，是因为数据延迟了吗？
