### ISSUE TITLE
直接打开艺术品地址会跳转到/start

### ISSUE THREAD

**Issue by bulusite** [TopBidder/bug-bounty#219]
直接打开https://sandbox.bidder.top/#/product/xxx后会跳转到https://sandbox.bidder.top/#/start
但是再次输入https://sandbox.bidder.top/#/product/xxx 就直接进入了,应该是前端路由的问题
---应该是进入任何页面都会跳到/start

在微信浏览器打开会直接白屏

0x4111b61D792db74fA1079244f54b0a06d83632E9

**Comment by lichking24** [comment]
已修复。
