### ISSUE TITLE
metamask 报错 ALERT: 交易出错。合约代码执行异常。

### ISSUE THREAD

**Issue by everyu** [TopBidder/bug-bounty#224]
https://sandbox.bidder.top/#/product/1376923774343057408 
竞拍这个艺术品，弹出metamask ，
然后metamask 报错 ALERT: 交易出错。合约代码执行异常。
其他艺术品竞拍正常。

0x793418b1b992f4225B55036DBA0F66C42168B543

**Comment by lichking24** [comment]
此拍品创建时的合约有bug，现已替换合约。感谢反馈。
