### ISSUE TITLE
前端请求应该加密  不应该明文传输

### ISSUE THREAD

**Issue by chenbo19931226** [TopBidder/bug-bounty#225]
![QQ图片20210401110201](https://user-images.githubusercontent.com/20835802/113237928-5dd99b00-92da-11eb-85d8-ef7251adc079.png)

**Comment by chenbo19931226** [comment]
0x4141023B1505294160f4eD0aB92496C8324d8A39

**Comment by lichking24** [comment]
感谢反馈。
后续优化期间我们会增加加密流程。
