### ISSUE TITLE
点击放大图片   查看的图片成了放大按钮

### ISSUE THREAD

**Issue by chenbo19931226** [TopBidder/bug-bounty#226]
![image](https://user-images.githubusercontent.com/20835802/113238155-c294f580-92da-11eb-9b83-6fbabe6ba734.png)
![image](https://user-images.githubusercontent.com/20835802/113238211-dcced380-92da-11eb-8f02-019ad5072c8a.png)
0x4141023B1505294160f4eD0aB92496C8324d8A39

**Comment by lichking24** [comment]
已修复。
文件上传机制已修改，新发艺术品不会出现此问题。
