### ISSUE TITLE
交易出错，合约代码执行异常

### ISSUE THREAD

**Issue by ShushiLi** [TopBidder/bug-bounty#227]
拍自己的id会出这种提示，拍别人的有时候也会遇到这种提示，不清楚是id问题还是什么，比如说拍艺术品地址为QmaGoJh65mC25BAoZoNDQdJi1JEVNZVC7ResTDhSa1oAFg的就会出现这种情况。
0x8ccFaFd8030B24548EE6193e126E6fA3196f3a69，、

**Comment by lichking24** [comment]
1. 目前已禁止拍自己的艺术品
2. 某段时间部署的合约有bug，上面的艺术品会出现此问题，现已替换合约
3. 同时出价会有此问题，旁边的自定义出价小提示中有说明
