### ISSUE TITLE
艺术家页面显示错误

### ISSUE THREAD

**Issue by bulusite** [TopBidder/bug-bounty#228]
如图1创作有一个,交易价为0.1ETH 但是图2艺术品总值 数量 均值 并没有显示
![bug1](https://user-images.githubusercontent.com/41330200/113254786-9a68bf00-92f9-11eb-878b-9b00971d2b04.png)
![bug2](https://user-images.githubusercontent.com/41330200/113254790-9b99ec00-92f9-11eb-9c85-dd1e69ff4486.png)

0x4111b61D792db74fA1079244f54b0a06d83632E9

**Comment by lichking24** [comment]
已修复
