### ISSUE TITLE
iPhone imtoken 显示错乱了 

### ISSUE THREAD

**Issue by cczufish** [TopBidder/bug-bounty#23]
-
![IMG_2908](https://user-images.githubusercontent.com/4083109/112805248-ede3ce80-90a7-11eb-9e40-2f60c774c313.PNG)
![IMG_2909](https://user-images.githubusercontent.com/4083109/112805269-f4724600-90a7-11eb-8caf-763f49a71fa4.PNG)

iPhone imtoken 显示错乱了 

0xE44E871C8328ACA6ae03921471DE177DEF1fC116

**Comment by lichking24** [comment]
暂未支持手机版本。估计玩些会进行适配。
