### ISSUE TITLE
建议这类提示弹窗都改成toast，降低操作成本，提升体验（优先级P2）

### ISSUE THREAD

**Issue by chencuocuo** [TopBidder/bug-bounty#231]
![image](https://user-images.githubusercontent.com/26619814/113273037-d2c6c800-930e-11eb-8e79-29eae2c8bc29.png)

我的测试地址：0x13734b9A36D34435e00418B248faD741580B7ac9

**Comment by chencuocuo** [comment]
![image](https://user-images.githubusercontent.com/26619814/113273673-7912cd80-930f-11eb-9a87-b38358c7d9aa.png)

同上

**Comment by lichking24** [comment]
已记录，感谢反馈
