### ISSUE TITLE
艺术品分享点击保存图片无反馈，点击复制图片，上面的缩略图会消失

### ISSUE THREAD

**Issue by chencuocuo** [TopBidder/bug-bounty#233]
![image](https://user-images.githubusercontent.com/26619814/113274544-664cc880-9310-11eb-97f0-2b07159489f6.png)

截图上面部分缩略图在点击【复制图片】后被隐藏了，不过这个问题不是必现的

【复制图片】、【保存图片】点击无反馈是必现的

我的测试地址：0x13734b9A36D34435e00418B248faD741580B7ac9

**Comment by lichking24** [comment]
分享仍在研发中。敬请期待。
