### ISSUE TITLE
艺术品的状态值使人困惑

### ISSUE THREAD

**Issue by chencuocuo** [TopBidder/bug-bounty#234]
![image](https://user-images.githubusercontent.com/26619814/113274988-dbb89900-9310-11eb-9b45-94746cd441af.png)

待审核、系统处理中是同一个状态吗？
待审核像是人工审核，系统处理中是自动处理？
建议在一个状态下，状态提示文案进行统一

**Comment by lichking24** [comment]
感谢反馈。
审核中的状态，按钮文案已修改。预计4.2上线。
