### ISSUE TITLE
交易记录 共有 {0} 条记录

### ISSUE THREAD

**Issue by lessl1001** [TopBidder/bug-bounty#236]
交易记录 共有 {0} 条记录

**Comment by lichking24** [comment]
已修复。
预计上线4.2日

**Comment by lessl1001** [comment]
0x1948c25458Cc3D57f8cE67bD2b5F84D743025ea8



Message&nbsp;From&nbsp;StyleSing



------------------ 原始邮件 ------------------
发件人: LichKing24 ***@***.***&gt;
发送时间: 2021年4月2日 15:34
收件人: TopBidder/bug-bounty ***@***.***&gt;
抄送: lessl1001 ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[TopBidder/bug-bounty] 交易记录 共有 {0} 条记录 (#236)





 
已修复。
 预计上线4.2日
