### ISSUE TITLE
页面显示问题

### ISSUE THREAD

**Issue by zm85** [TopBidder/bug-bounty#237]
![微信图片_20210402145734](https://user-images.githubusercontent.com/80375983/113390481-64dcd800-93c4-11eb-91ac-511a424b8b5f.png)
添加作品介绍时，要求为添加“4-100字符，仅限制中英文和数字”但实际添加不受限制，字符也可、字数没有真正限制。
以太地址：0x3dAd5288D0F9Ca63acB48940f349e0cF3832D311
谢谢。

**Comment by zm85** [comment]
以太地址：0x3dAd5288D0F9Ca63acB48940f349e0cF3832D311
谢谢。

**Comment by lichking24** [comment]
已修复。
