### ISSUE TITLE
浏览界面——搜索按钮点击无效

### ISSUE THREAD

**Issue by Ha1o** [TopBidder/bug-bounty#238]
![image](https://user-images.githubusercontent.com/9363544/113392294-7b386300-93c7-11eb-8917-0579e2da8672.png)

**Comment by lichking24** [comment]
已修复，预计4.2更新。

**Comment by Ha1o** [comment]
> 已修复，预计4.2更新。

我留个地址：
0xf062B3ab33A518Ef57e0039379A128CaF2e01AD8
谢谢老板
