### ISSUE TITLE
合约失败但是提示成功

### ISSUE THREAD

**Issue by HansiChan** [TopBidder/bug-bounty#24]
![image](https://user-images.githubusercontent.com/20923601/112805330-0b189d00-90a8-11eb-9628-d51e17568377.png)
![image](https://user-images.githubusercontent.com/20923601/112805350-11a71480-90a8-11eb-9c5b-08a196a25b08.png)

**Comment by HansiChan** [comment]
0x2F42fCd8D06A840C242814ea5AaAa60699C3D69c

**Comment by lichking24** [comment]
有问题的合约已替换。
已修复。
