### ISSUE TITLE
连接钱包bug

### ISSUE THREAD

**Issue by hayoial** [TopBidder/bug-bounty#240]
![Snipaste_2021-04-03_15-49-43](https://user-images.githubusercontent.com/25797796/113472237-71306600-9494-11eb-891b-7869388ec0cc.png)

![Snipaste_2021-04-03_15-48-08](https://user-images.githubusercontent.com/25797796/113472236-6ece0c00-9494-11eb-9888-fc3ae4c2ff7a.png)

莫名奇妙出现这个提示，后来多测试了几次发现bug如下：

网络差时，点一次登录，会跳出好几次metamask弹窗，如果都点击sign，会出现错误弹窗。

一旦出现此错误，只能关闭网页重新连接钱包。

**Comment by lichking24** [comment]
已加上loading层避免重复点击。
