### ISSUE TITLE
发布拍品的时候，无法获取艺术家信息

### ISSUE THREAD

**Issue by wY1k** [TopBidder/bug-bounty#241]
原因未知。
![Snipaste_2021-04-03_21-30-38](https://user-images.githubusercontent.com/57378842/113479891-14e53a80-94c4-11eb-8a3e-c0e4b26dadea.jpg)

0xf14364B58254a279afbB38e3Bc4ea951c6E7240E

**Comment by lichking24** [comment]
已修复。
