### ISSUE TITLE
English模式下只有头和尾是英文的，emmm

### ISSUE THREAD

**Issue by chencuocuo** [TopBidder/bug-bounty#242]
![image](https://user-images.githubusercontent.com/26619814/113480525-33006a00-94c7-11eb-872d-9640720d4177.png)

English模式下只有头和尾是英文的，可以后面再优化，优先级P1

我的测试地址：0x13734b9A36D34435e00418B248faD741580B7ac9

**Comment by gavlnxu** [comment]
应该是改了，但还有图标
![image](https://user-images.githubusercontent.com/16735902/113486846-4221f080-94a4-11eb-821f-8226ea32566f.png)

**Comment by lichking24** [comment]
已记录，中英文后续补全，感谢反馈！
