### ISSUE TITLE
自定义竞拍无效？

### ISSUE THREAD

**Issue by justlikeeth** [TopBidder/bug-bounty#243]
https://sandbox.bidder.top/#/product/1378613596635926528
这副作品0.05ETH的时候自定义竞拍，付了一个ETH
哈希：https://ropsten.etherscan.io/tx/0x79d81b1bcdaad46583be7d9cb6885f2029127194edb69147a79853932b429ea1
页面显示的时候我拍下价格是0.1ETH
0.15ETH 的时候我自定义竞拍一个以太
买下价格还是0.2ETH

**Comment by lichking24** [comment]
自定义竞拍的意思并不是按照出价竞拍。提示已经加上，在首页按钮旁边。多余的钱会自动退回钱包。
