### ISSUE TITLE
首页数据不更新/更新慢

### ISSUE THREAD

**Issue by justlikeeth** [TopBidder/bug-bounty#244]
![image](https://user-images.githubusercontent.com/64671546/113502803-144eb180-9561-11eb-90c6-3f8cd638382e.png)
某些时候刷新数据不更新
![image](https://user-images.githubusercontent.com/64671546/113502818-26c8eb00-9561-11eb-925b-932865b059b4.png)
点进去已经0.3ETH了

**Comment by lichking24** [comment]
已修复。
