### ISSUE TITLE
自定义竞拍问题

### ISSUE THREAD

**Issue by thisjim** [TopBidder/bug-bounty#245]
竞拍作品现价1eth，点击自定义竞拍，随意填写10eth进行竞拍，为何拍得的价格不是10eth.
<img width="338" alt="微信截图_20210404191409" src="https://user-images.githubusercontent.com/81882060/113507880-9bab1d80-957f-11eb-9689-20566f9275c6.png">
<img width="279" alt="微信截图_20210404191425" src="https://user-images.githubusercontent.com/81882060/113507883-9cdc4a80-957f-11eb-8b1b-3833be124a0e.png">

0x86F2AA93fDA00Bbeb0C6bc86021f3332597C0004

**Comment by lichking24** [comment]
自定义竞拍的含义首页按钮旁边有提示，多余钱会退回钱包。
