### ISSUE TITLE
浏览页收藏家显示问题

### ISSUE THREAD

**Issue by thisjim** [TopBidder/bug-bounty#246]
拍得作品后，多次刷新浏览页，作品显示收藏家还是上一位竞拍者。显示有误
0x86F2AA93fDA00Bbeb0C6bc86021f3332597C0004
<img width="387" alt="微信截图_20210404195708" src="https://user-images.githubusercontent.com/81882060/113508050-6bb04a00-9580-11eb-9830-eb9fa1cf8f4d.png">
<img width="737" alt="微信截图_20210404195737" src="https://user-images.githubusercontent.com/81882060/113508052-6d7a0d80-9580-11eb-804c-098edd0e4678.png">

**Comment by lichking24** [comment]
已修复。
