### ISSUE TITLE
浏览页作品价格数据显示有误

### ISSUE THREAD

**Issue by thisjim** [TopBidder/bug-bounty#247]
浏览页作品价格数据显示有误，数据显示不及时。
0x86F2AA93fDA00Bbeb0C6bc86021f3332597C0004
<img width="737" alt="微信截图_20210404195737" src="https://user-images.githubusercontent.com/81882060/113508169-16286d00-9581-11eb-8e6b-a31b815eb48c.png">
<img width="1013" alt="微信截图_20210404200435" src="https://user-images.githubusercontent.com/81882060/113508173-17f23080-9581-11eb-830a-7c95bfc8a08a.png">

**Comment by lichking24** [comment]
已修复。
