### ISSUE TITLE
排行榜-TOP艺术家排序问题

### ISSUE THREAD

**Issue by qdpoboy** [TopBidder/bug-bounty#252]
![图片](https://user-images.githubusercontent.com/8943903/113658826-5e57a480-96d3-11eb-88ad-94888aa4571c.png)  

点击按 “招牌艺术品” 排序，只有首次点击时才有排序效果，往后再点击没有任何变化

0x349FB1e6Cd729df73e2A6E739E556ae720E2aD54

**Comment by JameseLi** [comment]
fix

**Comment by lichking24** [comment]
已修复。
