### ISSUE TITLE
排行榜-TOP艺术品排序肩头问题

### ISSUE THREAD

**Issue by qdpoboy** [TopBidder/bug-bounty#253]
点击价格排序，上下箭头没有变化
![F38D320E-11FE-479D-B42A-42DD5A52BADA](https://user-images.githubusercontent.com/8943903/113660449-ae843600-96d6-11eb-9112-8df68edccc84.png)

0x349FB1e6Cd729df73e2A6E739E556ae720E2aD54

**Comment by lichking24** [comment]
已修复 预计4.7上线。 v0.0.21

**Comment by lichking24** [comment]
已修复。
