### ISSUE TITLE
切换英文，弹窗提示仍然为中文

### ISSUE THREAD

**Issue by qdpoboy** [TopBidder/bug-bounty#254]
![604DE21D-1E8C-4AA6-8A9A-3F95C67D3058](https://user-images.githubusercontent.com/8943903/113660572-ff942a00-96d6-11eb-8dad-9d1314cbdfd7.png)

0x349FB1e6Cd729df73e2A6E739E556ae720E2aD54

**Comment by qdpoboy** [comment]
![E69989FF-DEC4-4E75-B067-B17D4D79A74E](https://user-images.githubusercontent.com/8943903/113660727-54d03b80-96d7-11eb-9caf-672cdc3541d9.png)

这种弹窗应该都没做英文

**Comment by qdpoboy** [comment]
个人中心，英文下，这个人很懒，没有留下什么…也没做英文处理

**Comment by lichking24** [comment]
已记录，中英文内容会尽快补全，感谢反馈。
