### ISSUE TITLE
邀请记录英文下，查看更多没有转为英文

### ISSUE THREAD

**Issue by qdpoboy** [TopBidder/bug-bounty#256]
0x349FB1e6Cd729df73e2A6E739E556ae720E2aD54

![2B3D61B5-D723-4666-ADDF-8F5E550CEB3A](https://user-images.githubusercontent.com/8943903/113661203-3e76af80-96d8-11eb-8da1-ebcde2b09bb3.png)

**Comment by lichking24** [comment]
已修复。
