### ISSUE TITLE
英文状态下，title没转英文

### ISSUE THREAD

**Issue by qdpoboy** [TopBidder/bug-bounty#257]
此类都需要改一下

0x349FB1e6Cd729df73e2A6E739E556ae720E2aD54

![C94595ED-ADAD-48F9-B2D0-A6DE1309D7BD](https://user-images.githubusercontent.com/8943903/113661431-a6c59100-96d8-11eb-83c3-dcaa25a5b575.png)

**Comment by lichking24** [comment]
已修复。v0.0.20
