### ISSUE TITLE
显示错误

### ISSUE THREAD

**Issue by pipi333** [TopBidder/bug-bounty#259]
![image](https://user-images.githubusercontent.com/37148466/113973207-80395e80-986e-11eb-954e-79955e7690e3.png)
我收藏的两幅画不是一个作者 但是却显示作者名字都是一个人 应该是显示错误了吧？
Creampp提交~

**Comment by lichking24** [comment]
已修复。

**Comment by pipi333** [comment]
0xEccC484DD4093F62fC24c4725800013FBc2C1D15
