### ISSUE TITLE
测试网空投页面活动重复且无操作按钮

### ISSUE THREAD

**Issue by fpChan** [TopBidder/bug-bounty#261]
## 问题描述
https://sandbox.bidder.top/#/airdrop
<img width="1275" alt="截屏2021-04-09 下午5 29 22" src="https://user-images.githubusercontent.com/29588923/114160540-a0921780-9959-11eb-97e6-b732bf0f6ee4.png">

## ETH 地址

0xa6a29572fC865B554e710182a76a7F80F339a6DF

**Comment by lichking24** [comment]
非重复。测试脏数据。
