### ISSUE TITLE
Metamask手机钱包，点击查看全部，链接打不开

### ISSUE THREAD

**Issue by bld2018** [TopBidder/bug-bounty#28]
![IMG_20210329_160354](https://user-images.githubusercontent.com/35189867/112805681-87c16200-903b-11eb-9ed5-65abb6ce1973.jpg)

**Comment by bld2018** [comment]
0x6b69417C8327407F97E3616619f1826540c1c7D0

**Comment by lichking24** [comment]
暂未适配手机端，后续将完成适配。
