### ISSUE TITLE
无法申请成为艺术家

### ISSUE THREAD

**Issue by hulia1** [TopBidder/bug-bounty#29]
![image](https://user-images.githubusercontent.com/76275067/112805620-65196280-90a8-11eb-971e-9bc11a5c20c3.png)
签名推特地址的时候 总是提示我   请填写个人Twitter主页地址   但是我已经填了推特地址。

0xA1a52925369C3870aACF26dEcf7A8727e5a47FB7

**Comment by c-gongzhihui** [comment]
上面是您没有填写Twitter地址只填写了Tweet地址，不过目前已经简化申请流程，只需要Tweet地址
