### ISSUE TITLE
如何解绑twitter账号，是否可以支持多个钱包绑定到一个twitter账号

### ISSUE THREAD

**Issue by k1ic** [TopBidder/bug-bounty#32]
![image](https://user-images.githubusercontent.com/5465932/112805878-bfb2be80-90a8-11eb-9c58-4c891d138f84.png)

**Comment by lichking24** [comment]
暂时不可解锁，已列入需求，后续进行产品优化。

**Comment by k1ic** [comment]
0xD67c34169b372d5B3932c548a940D4Ea74Fe7aF5
twitter ki1c234
可否帮忙手工解绑下，多谢
