### ISSUE TITLE
点击竞拍一直处于处理中状态

### ISSUE THREAD

**Issue by HansiChan** [TopBidder/bug-bounty#33]
![image](https://user-images.githubusercontent.com/20923601/112806009-e40e9b00-90a8-11eb-82b9-6e4b799fbd4c.png)
竞拍链接：https://sandbox.bidder.top/#/product/1376445246258417664

**Comment by HansiChan** [comment]
0x2F42fCd8D06A840C242814ea5AaAa60699C3D69c

**Comment by lichking24** [comment]
Fixed
