### ISSUE TITLE
申请不上艺术家

### ISSUE THREAD

**Issue by hulia1** [TopBidder/bug-bounty#35]
![image](https://user-images.githubusercontent.com/76275067/112805967-d9ec9c80-90a8-11eb-9024-9220a130d29b.png)

生成签名的之后，推特地址会自动清空，提示信息不完善，按照要求弄完，也申请不上艺术家。

0xA1a52925369C3870aACF26dEcf7A8727e5a47FB7

**Comment by lichking24** [comment]
已修复。流程优化。
