### ISSUE TITLE
推特无法验证

### ISSUE THREAD

**Issue by ycl1216919** [TopBidder/bug-bounty#36]
使用推特账号（粉丝数3）验证时无法验证，且并无提示无法验证原因。
![微信截图_20210329170746](https://user-images.githubusercontent.com/36100212/112806096-60a57780-90b1-11eb-8ed3-f5d2f69347f9.png)

**Comment by ycl1216919** [comment]
删除签名Tweet地址的?s=20后可以验证，确认为bug

**Comment by lichking24** [comment]
已修复。感谢反馈！
