### ISSUE TITLE
网页应该多显示些竞拍记录

### ISSUE THREAD

**Issue by xiaoyaoyou116** [TopBidder/bug-bounty#37]
这个竞拍记录只显示五个人，网页应该多显示些竞拍记录，以便参考。
我的地址：0xA6Ff7FD5b13aceFb6a717A07C5Ba93d6Dbd993c3
![Snipaste_2021-03-29_16-07-22](https://user-images.githubusercontent.com/54977092/112806860-d279c300-90a9-11eb-8e5c-e08508b2d965.png)

**Comment by lichking24** [comment]
显示全部记录，那五个的地方，可以往下滚动查看～
