### ISSUE TITLE
MetaMask弹出合约代码异常

### ISSUE THREAD

**Issue by huaigu** [TopBidder/bug-bounty#38]
在未登录的情况下，参与竞拍，会提示合约异常。

![bug](https://user-images.githubusercontent.com/626809/112806370-48315f00-90a9-11eb-9dc7-47281ce53486.png)

https://sandbox.bidder.top/#/product/1376415488669782016
点击竞拍，metamask弹出合约错误。

MyAddress：
0xE913c0f42fB60F85Bd43bDdDAf4e004135eF318c

**Comment by lichking24** [comment]
已修复。
