### ISSUE TITLE
Wrong price displayed after my last bid

### ISSUE THREAD

**Issue by Gigatron** [TopBidder/bug-bounty#4]
I submitted a customized bid with 5ETH, but the next auction price shown on the page is below 5ETH.  Please see the following snapshot and transaction link.

![image](https://user-images.githubusercontent.com/585756/112803105-86c51a80-90a5-11eb-95f5-c3b6689cd61d.png)

https://ropsten.etherscan.io/tx/0xe22c8361b92366adaf8019a82847a1a8bce280785724f232cc80ae6e098c5c5e

My ETH address is 0xff2fed9cb48196ec35fd97b290c583e7a63b17b7.

**Comment by lichking24** [comment]
Fixed

**Comment by davidqw** [comment]
this is a feature, not bug. the amount more than 110% of orginal price will be send back to the bidder

**Comment by Gigatron** [comment]
So the diy offer is an upper bound? i.e. the transaction goes through if the next bid price is less than the diy price, right? 
If that's what you mean, I feel the text on the button is a bit misleading...

**Comment by davidqw** [comment]
> So the diy offer is an upper bound? i.e. the transaction goes through if the next bid price is less than the diy price, right?
> If that's what you mean, I feel the text on the button is a bit misleading...

you are right, the upper bound, there will be FAQ to answer this mechanism
