### ISSUE TITLE
竞拍成功后竞拍次数不会更新

### ISSUE THREAD

**Issue by HansiChan** [TopBidder/bug-bounty#41]
![image](https://user-images.githubusercontent.com/20923601/112806515-6d25d200-90a9-11eb-8bfc-109d4ca7d7bf.png)
交易链接：https://ropsten.etherscan.io/tx/0x190fc74bb74837bee4f5f33660e08e003cdea2d611638c31a95e17393e17becc
商品链接：https://sandbox.bidder.top/#/product/1376206307710865408

**Comment by HansiChan** [comment]
0x2F42fCd8D06A840C242814ea5AaAa60699C3D69c

**Comment by lichking24** [comment]
已修复。
