### ISSUE TITLE
产品详情页滚动到底部时，页面布局错乱

### ISSUE THREAD

**Issue by lixuejiang** [TopBidder/bug-bounty#5]
![image](https://user-images.githubusercontent.com/5007080/112803482-e7ecee00-90a5-11eb-921d-edef4c647c5f.png)

https://sandbox.bidder.top/#/product/1376156797966094336

钱包地址：0x3DF10334531A3c86590245e12Be0104Dd3459159

**Comment by lichking24** [comment]
已修复。
