### ISSUE TITLE
比特派钱包无法连接并且浏览器显示有些问题

### ISSUE THREAD

**Issue by specterofnet** [TopBidder/bug-bounty#51]
![1891006445](https://user-images.githubusercontent.com/18514016/112807427-795e5f00-90aa-11eb-80bc-673133b6c0af.jpg)
My address: 0x9f2567154CBC7dbFcd4b7585F082c58F2Aad2eCb

**Comment by lichking24** [comment]
暂未支持手机端钱包，后续将适配，感谢反馈！
