### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by hulia1** [TopBidder/bug-bounty#53]
![image](https://user-images.githubusercontent.com/76275067/112807517-9430d380-90aa-11eb-83f3-f14330767d8c.png)
建议增加竞拍记录，成功，失败，竞拍中的链上记录。

0xA1a52925369C3870aACF26dEcf7A8727e5a47FB7

**Comment by lichking24** [comment]
内容在：右上角头像-》下拉菜单-》交易记录。
后续将补充该记录的成功失败状态。
感谢反馈！
