### ISSUE TITLE
自定义竞拍出现错误

### ISSUE THREAD

**Issue by xiaoyaoyou116** [TopBidder/bug-bounty#55]
![Snipaste_2021-03-29_16-18-11](https://user-images.githubusercontent.com/54977092/112807490-8c712f00-90aa-11eb-9f9e-3d66f29e895c.png)
自定义竞拍出现错误，合约代码执行异常
我的钱包地址：0xA6Ff7FD5b13aceFb6a717A07C5Ba93d6Dbd993c3

**Comment by lichking24** [comment]
已修复出价低于当前价格的bug。
