### ISSUE TITLE
点击下方收入管理跳转的地址不对

### ISSUE THREAD

**Issue by protonmailv5** [TopBidder/bug-bounty#59]
![QQ截图20210329162138](https://user-images.githubusercontent.com/61324752/112807918-043f5980-90ab-11eb-8526-02a553808a5a.jpg)
入图所示，点击下方收入管理后跳转的URL地址不对，正确的地址应该是 https://sandbox.bidder.top/#/incomes

**Comment by lichking24** [comment]
已修复。
