### ISSUE TITLE
首页作品hover pointer的范围小于 链接 可点击范围

### ISSUE THREAD

**Issue by WillXing** [TopBidder/bug-bounty#61]
![image](https://user-images.githubusercontent.com/4098617/112808212-3f568280-90d5-11eb-803f-8a0244d6a927.png)

图中红圈是可以点击进入作品的，但是hover没有pointer。 可能应该缩小可点击进入作品的链接范围

0x642Bf2b93DCab8e3FDbF9bFE2382a968F4a1785c

**Comment by lichking24** [comment]
已修复。
