### ISSUE TITLE
预览图片问题

### ISSUE THREAD

**Issue by LidamaoHub** [TopBidder/bug-bounty#62]
![image](https://user-images.githubusercontent.com/6832146/112807670-be829100-90aa-11eb-93ad-e381cf2f631c.png)

点击放大图片后会请求和301四次不同地址,且数据量巨大.

建议修改方案

1.图片地址预处理,减少301
2.静态资源做Cache-control,减少重复打开时重复加载(艺术品本身不会有变化,所以不需要重复加载)
3.大图上传时做压缩处理,减少加载失败风险
4.大图展示组件下方放置check origin 来保存未压缩原图

**Comment by lichking24** [comment]
已记录，将优化图片的问题，感谢反馈！
