### ISSUE TITLE
Metamask手机钱包竞拍下面的围观和分享链接点击无响应

### ISSUE THREAD

**Issue by bld2018** [TopBidder/bug-bounty#65]
![IMG_20210329_161558](https://user-images.githubusercontent.com/35189867/112808444-96f5df00-903e-11eb-8099-a23860a05094.jpg)

**Comment by bld2018** [comment]
0x6b69417C8327407F97E3616619f1826540c1c7D0

**Comment by lichking24** [comment]
暂未适配手机端，后续将会进行适配。
