### ISSUE TITLE
UI显示问题，未正确显示数字

### ISSUE THREAD

**Issue by YaakovHuang** [TopBidder/bug-bounty#67]
描述：
艺术家 --> 作品最多 下面赤金这个用户下面ETH数量显示不正确

[位置](https://sandbox.bidder.top/#/artists)

<img width="1631" alt="WX20210329-162413@2x" src="https://user-images.githubusercontent.com/9527803/112808556-ad864f80-90ab-11eb-90ca-aa26128791fd.png">

**Comment by lichking24** [comment]
已修复。
