### ISSUE TITLE
邮箱没有格式检查可以瞎基波填

### ISSUE THREAD

**Issue by WillXing** [TopBidder/bug-bounty#68]
个人信息更新的时候 邮箱没有格式检查 可以乱更新

![image](https://user-images.githubusercontent.com/4098617/112808928-feab3900-90d5-11eb-8d4c-7b8164f2349a.png)

0x642Bf2b93DCab8e3FDbF9bFE2382a968F4a1785c

**Comment by lichking24** [comment]
已修复。v0.0.20
