### ISSUE TITLE
个人主页不显示已购买/被买走的作品

### ISSUE THREAD

**Issue by Deahow** [TopBidder/bug-bounty#7]
我购买画作后查询个人主页不能看到已经购买的画作，被竞拍的画作同样也不能查看记录

**Comment by xiaobin428** [comment]
排行榜无法查看上榜作者作品详细内容
<img width="878" alt="1" src="https://user-images.githubusercontent.com/36256369/112816814-5e90e800-90b4-11eb-9f6b-1d335d198ecb.png">
个人中心不显示竞拍收藏作品详细内容
<img width="956" alt="2" src="https://user-images.githubusercontent.com/36256369/112816941-7cf6e380-90b4-11eb-95e2-df9882516419.png">
我的地址：0x5F1DbF6B9dbA1B53dA4d7d08996bC866eE9E93E3

**Comment by lichking24** [comment]
已修复。
