### ISSUE TITLE
大部分可跳转链接和功能性链接css不一致

### ISSUE THREAD

**Issue by LidamaoHub** [TopBidder/bug-bounty#70]
![WechatIMG1557](https://user-images.githubusercontent.com/6832146/112808762-eaeadd00-90ab-11eb-9221-0f8986b4f0ff.jpeg)

功能性或者可点击文字内容应该统一添加
```
cursor:pointer
```
来表现可点击作用

**Comment by lichking24** [comment]
已修复。
