### ISSUE TITLE
提交一些bug

### ISSUE THREAD

**Issue by alixsun0215** [TopBidder/bug-bounty#75]
1.在艺术家艺术品均价排序的时候
![image](https://user-images.githubusercontent.com/26176928/112808711-ddcdee00-90ab-11eb-9525-9f84fa446b60.png)
![image](https://user-images.githubusercontent.com/26176928/112808764-eb837380-90ab-11eb-9081-739decf8df63.png)
出现了前后顺序跌到的问题。
2.自定义竞拍提交成功以后 合约出错！
![image](https://user-images.githubusercontent.com/26176928/112810203-60a37880-90ad-11eb-9cdd-7caddbecd35b.png)
0x8046F1a06478A151027b501caA65e841D87Ec876

**Comment by lichking24** [comment]
均已修复。
