### ISSUE TITLE
推特无法验证

### ISSUE THREAD

**Issue by newgitname** [TopBidder/bug-bounty#76]
申请成为艺术家的时，推特无法验证
![截屏2021-03-29 下午4 24 31](https://user-images.githubusercontent.com/44631164/112809165-4f0da100-90ac-11eb-82d6-78f8b4241fef.png)

我的地址是 0xB3cfaa16368A907BF8f195E27edA60b0477a8a5c

**Comment by c-gongzhihui** [comment]
已修复
