### ISSUE TITLE
个人中心竞拍信息未正确显示

### ISSUE THREAD

**Issue by YaakovHuang** [TopBidder/bug-bounty#77]
描述:
个人中心这里的竞拍信息未正确显示，我是有成功参与竞拍的。

<img width="1499" alt="WX20210329-163243@2x" src="https://user-images.githubusercontent.com/9527803/112809365-84b28a00-90ac-11eb-919a-0092ece8e94c.png">

**Comment by c-gongzhihui** [comment]
已修复
