### ISSUE TITLE
发布时长成了负数

### ISSUE THREAD

**Issue by WillXing** [TopBidder/bug-bounty#78]
凡尔赛大侠！

![image](https://user-images.githubusercontent.com/4098617/112809590-a6c10200-90d6-11eb-8f4e-206ffb63e9db.png)

作品链接：https://sandbox.bidder.top/#/product/1376448373149798400

0x642Bf2b93DCab8e3FDbF9bFE2382a968F4a1785c

**Comment by lichking24** [comment]
已修复。
