### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by zm85** [TopBidder/bug-bounty#79]
1、**对于拍卖直观感受：**买家竞拍时，对于创作的艺术品信息要有充分的了解，官方是否可以加上对于卖家（或艺术品信息）等重要描述审核环节？这样更能直观的让买家了解艺术品的来源、品质，官方是否给“盖章”是关键一步。
2、页面设置最好将艺术品进行分类收集，对于更加有倾向性的选择有很大帮助，挑选自己喜欢的类别让拍卖的成交率会更高。
3、对于拍卖品折扣优惠部分，更直接的到达优惠艺术品选择区，引流初入学者，让拍卖变得更加容易。
4、对于已经拍卖的收藏品的记录查询，收藏家将艺术品收藏成功后，最好有记录跟踪，便于在转让时有更有价值的参考。
5、对于拍卖热度加”标签“，竞拍火热时，建议将热度标签增加在首页热推，进入网站后能直接看到正在热拍中的作品，更直观的引流艺术爱好者的关注度。
谢谢，这是我对页面设置的一些只管感受，仅从便捷、舒适、清晰角度出发提出的一些不成熟的建议。
0x3dAd5288D0F9Ca63acB48940f349e0cF3832D311

**Comment by lichking24** [comment]
感谢反馈！
1、2、4、5建议我们将在后续进行优化。
3 我们并没有折扣优惠的说法啊？
