### ISSUE TITLE
BUG1

### ISSUE THREAD

**Issue by mydigg** [TopBidder/bug-bounty#81]
can't bidder.   as picture.
#拍下大白菜，无法支付费用和GAS。

**Comment by mydigg** [comment]
can't bidder. as picture.
#拍下大白菜，无法支付费用和GAS。
![Uploading 1111.png…]()

**Comment by mydigg** [comment]
![222](https://user-images.githubusercontent.com/76777334/112813229-8e3df100-90b0-11eb-91c4-10383668d22a.png)
BUG2   .        0x053671DA56CB9f5C55698244c95fCf1C706a54E7

**Comment by mydigg** [comment]
BUG3 无法推特认证成为艺术家，老是错误，换了N次。还是错误
![嘻嘻嘻](https://user-images.githubusercontent.com/76777334/112816781-5769da00-90b4-11eb-8dc0-d0198e42624b.png)

**Comment by lichking24** [comment]
均已修复。
无法拍卖的是在错误合约上创建的，目前合约已替换。
感谢反馈！
