### ISSUE TITLE
直接拍和自定义拍都提示合约代码执行异常

### ISSUE THREAD

**Issue by cjayz001** [TopBidder/bug-bounty#82]
![test1](https://user-images.githubusercontent.com/76425476/112809765-f094f280-90ac-11eb-8b10-736192688918.JPG)
![test2](https://user-images.githubusercontent.com/76425476/112809800-fc80b480-90ac-11eb-93de-e2fd52354903.JPG)
如图所示，直接拍和自定义拍都提示合约代码执行异常。

**Comment by cjayz001** [comment]
![test3](https://user-images.githubusercontent.com/76425476/112810219-64cf9600-90ad-11eb-8566-061d419deaaf.JPG)
网站首页的围观和分享按钮无效，没法直接点击

**Comment by cjayz001** [comment]
![test4](https://user-images.githubusercontent.com/76425476/112810847-09ea6e80-90ae-11eb-8897-aac55d32aae3.JPG)
首页查看全部按键全部失效

**Comment by lichking24** [comment]
均已修复。
白菜的合约有bug，已替换。
感谢！
