### ISSUE TITLE
Metamask手机钱包点击艺术家和收藏家，跳转后环境错误

### ISSUE THREAD

**Issue by bld2018** [TopBidder/bug-bounty#87]
![IMG_20210329_163413](https://user-images.githubusercontent.com/35189867/112810749-fb19a280-9040-11eb-83be-78937d251496.jpg)
![Screenshot_2021-03-29-16-33-33-881_com android browser](https://user-images.githubusercontent.com/35189867/112810759-fd7bfc80-9040-11eb-9b5c-70a7f3b4a2ac.jpg)

**Comment by bld2018** [comment]
0x6b69417C8327407F97E3616619f1826540c1c7D0

**Comment by bld2018** [comment]
直接跳转到浏览器，不是以太坊环境。

**Comment by lichking24** [comment]
手机端仍在开发中，敬请期待。
