### ISSUE TITLE
艺术品详情页的收藏家和预览时的收藏家不一致

### ISSUE THREAD

**Issue by WillXing** [TopBidder/bug-bounty#98]
详情页
![image](https://user-images.githubusercontent.com/4098617/112812028-23ed7680-90d9-11eb-8803-bf76a43d1cff.png)

首页

![image](https://user-images.githubusercontent.com/4098617/112812126-3cf62780-90d9-11eb-8231-08e49f931d35.png)

我刷新了的 老哥

**Comment by lichking24** [comment]
已修复。
